//
//  CharacterRouter.swift
//  TABTest
//
//  Created by master on 4/21/18.
//  Copyright (c) 2018 neemo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharacterRoutingLogic
{
  func routeToChallengeDetail(segue: UIStoryboardSegue?)
}

protocol CharacterDataPassing
{
  var dataStore: CharacterDataStore? { get }
}

class CharacterRouter: NSObject, CharacterRoutingLogic, CharacterDataPassing
{
  weak var viewController: CharacterViewController?
  var dataStore: CharacterDataStore?
  
  // MARK: Routing
  
  func routeToChallengeDetail(segue: UIStoryboardSegue?)
  {
        if let segue = segue
        {
            var destinationVC = segue.destination as! CharacterDetailViewController
            passDataToDetail(source: dataStore!, destination: &destinationVC)
        }
        else
        {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            var destinationVC = storyboard.instantiateViewController(withIdentifier: "CharacterDetailViewController") as! CharacterDetailViewController
            
            passDataToDetail(source: dataStore!, destination: &destinationVC)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }

  // MARK: Navigation
  
   func navigateToSomewhere(source: CharacterViewController, destination: CharacterDetailViewController)
   {
        source.show(destination, sender: nil)
    }
  
   //MARK: Passing data
  
  func passDataToDetail(source: CharacterDataStore, destination: inout CharacterDetailViewController)
  {
     destination.character = source.selectedCharacter
  }
}
